
package hwdroid.util;

@SuppressWarnings("all")
public class Config {

    private Config() {
    }

    /**
     * the switch control all the animations in AUI whether display.
     */
    public static final boolean HW_AUI_ANIMATION_ENABLE = true;

    private static final int HW_LOG_LEVEL_INFO = 3;
    private static final int HW_LOG_LEVEL_WARNING = 2;
    private static final int HW_LOG_LEVEL_ERROR = 1;
    private static final int HW_LOG_LEVEL_NONE = 0;

    /**
     * Set this flag to HW_LOG_LEVEL_NONE when releasing your application in
     * order to remove all logs generated by HWDroid.
     */
    private static final int HW_LOG_LEVEL = HW_LOG_LEVEL_INFO;

    /**
     * Indicates whether info logs are enabled. This should be true only when
     * developing/debugging an application/the library
     */
    public static final boolean HW_INFO_LOGS_ENABLED = (HW_LOG_LEVEL == HW_LOG_LEVEL_INFO);

    /**
     * Indicates whether warning logs are enabled
     */
    public static final boolean HW_WARNING_LOGS_ENABLED = HW_INFO_LOGS_ENABLED || (HW_LOG_LEVEL == HW_LOG_LEVEL_WARNING);

    /**
     * Indicates whether error logs are enabled. Error logs are usually always
     * enabled, even in production releases.
     */
    public static final boolean HW_ERROR_LOGS_ENABLED = HW_WARNING_LOGS_ENABLED || (HW_LOG_LEVEL == HW_LOG_LEVEL_ERROR);

}
